# Generated by Django 4.0.2 on 2022-03-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=25)),
                ('port', models.CharField(blank=True, max_length=15)),
                ('protocol', models.CharField(blank=True, max_length=6)),
                ('anonymity', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('uptime', models.CharField(blank=True, max_length=15)),
                ('response', models.CharField(blank=True, max_length=15)),
                ('transfer', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
