# Generated by Django 4.0.2 on 2022-03-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_anonymity_data_litro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='local',
            new_name='cidade',
        ),
        migrations.AddField(
            model_name='data',
            name='endereco',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
