# Generated by Django 4.0.2 on 2022-03-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_local_data_cidade_data_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='nome_intituicao',
        ),
        migrations.AddField(
            model_name='data',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
