# Generated by Django 4.0.3 on 2022-03-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='anonymity',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='city',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='ip_address',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='data',
            name='port',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='protocol',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='data',
            name='region',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='response',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='transfer',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='uptime',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
